"""Scaffold a new training deck folder from skill templates.

Creates:
  <deck-dir>/
    deck.html       # reveal.js, brand-themed
    slides.md       # starter content with title + agenda placeholders
    routes.json     # screenshot map (empty stub)
    screenshots/
    notes/outline.md

Usage:
    python scaffold_deck.py \
        --out docs/training/action-tracker \
        --title "Action Tracker — User Training" \
        --module "Action Tracker" \
        --brand /path/to/brand.json \
        --logo public/fep-logo/FEP-sidebar.svg
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

TEMPLATES = Path(__file__).parent.parent / "templates"

STARTER_SLIDES = """\
<!-- Generated by training-deck-builder. Edit freely. -->

<!-- .slide: class="title-slide" -->

# {title}

### {subtitle}

<div class="meta">
{module} · {date} · v1.0
</div>

---

## Agenda

- What is {module} and where does it live in the app
- Roles covered in this deck
- Walkthroughs by role
- Cross-cutting concerns
- Q&A

Note:
Set expectations for ~{minutes} minutes total. Encourage interruptions.

---

## Module overview

> Replace this with a 1-paragraph plain-English description of the module.

- Purpose
- Where it lives in the navigation
- How it relates to other modules

---

<!-- .slide: class="role-cover" -->

# Role: {first_role}

> One-sentence definition of who this person is and what they care about.

---

## TODO: walkthroughs

Add per-role walkthrough slides here. Use this template per slide:

```
<!-- .slide: class="walkthrough" -->

## Walkthrough title

<div class="screenshot-wrap">
  <img src="screenshots/<id>.png" class="screenshot" alt="...">
</div>

<span class="step">1</span> First step
<span class="step">2</span> Second step
<span class="step">3</span> Third step

Note:
Speaker note...
```
"""

ROUTES_STUB = {
    "deck": "<deck-slug>",
    "baseUrl": "http://localhost:3000",
    "viewport": {"width": 1440, "height": 900},
    "auth": {"mode": "manual", "loginRoute": "/"},
    "screenshots": [],
}

OUTLINE_STARTER = """\
# Outline draft

Edit this, get user sign-off, then start filling in slides.md.

## Roles
- ...

## Walkthroughs by role
- ...
"""


def render_html(brand: dict, title: str, logo_path: str) -> str:
    tpl = (TEMPLATES / "deck-template.html").read_text(encoding="utf-8")
    return (
        tpl.replace("{{DECK_TITLE}}", title)
        .replace("{{BRAND_PRIMARY}}", brand.get("primary", "#37A130"))
        .replace("{{BRAND_PRIMARY_DARK}}", brand.get("primaryDark", "#2F8E2A"))
        .replace("{{BRAND_PRIMARY_LIGHT}}", brand.get("primaryLight", "#E9FFF3"))
        .replace("{{BRAND_TEXT}}", brand.get("text", "#000000"))
        .replace("{{BRAND_MUTED}}", brand.get("muted", "#9CA3AF"))
        .replace("{{BRAND_BORDER}}", brand.get("border", "#D2D7E0"))
        .replace("{{BRAND_SUCCESS}}", brand.get("success", "#04A850"))
        .replace("{{BRAND_WARNING}}", brand.get("warning", "#D97706"))
        .replace("{{BRAND_ERROR}}", brand.get("error", "#B81719"))
        .replace("{{BRAND_FONT}}", brand.get("font", "Roboto"))
        .replace("{{LOGO_PATH}}", logo_path)
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--title", required=True)
    ap.add_argument("--module", required=True)
    ap.add_argument("--subtitle", default="Role-based walkthrough training")
    ap.add_argument("--first-role", default="<First role>")
    ap.add_argument("--minutes", default="30")
    ap.add_argument("--logo", default="")
    ap.add_argument("--brand", default=None, help="Path to brand.json (else uses defaults)")
    ap.add_argument("--date", default="")
    args = ap.parse_args()

    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    (out / "screenshots").mkdir(exist_ok=True)
    (out / "notes").mkdir(exist_ok=True)

    if args.brand:
        brand = json.loads(Path(args.brand).read_text())
    else:
        brand = {}

    # Logo path: resolve relative to deck.html location
    logo_path = args.logo
    if logo_path and not logo_path.startswith(("http://", "https://", "/")):
        # Make it relative to the deck.html
        try:
            logo_abs = Path(logo_path).resolve()
            logo_path = str(Path("..").joinpath(*Path("../../").parts).joinpath(logo_abs.relative_to(Path.cwd())))
        except Exception:
            pass

    html = render_html(brand, args.title, logo_path)
    (out / "deck.html").write_text(html, encoding="utf-8")

    slides = STARTER_SLIDES.format(
        title=args.title,
        subtitle=args.subtitle,
        module=args.module,
        first_role=args.first_role,
        minutes=args.minutes,
        date=args.date,
    )
    (out / "slides.md").write_text(slides, encoding="utf-8")

    routes = dict(ROUTES_STUB)
    routes["deck"] = out.name
    (out / "routes.json").write_text(json.dumps(routes, indent=2), encoding="utf-8")

    (out / "notes" / "outline.md").write_text(OUTLINE_STARTER, encoding="utf-8")

    print(f"Scaffolded deck at {out}")
    print("Next steps:")
    print(f"  1. Edit {out}/notes/outline.md and get user sign-off")
    print(f"  2. Fill in {out}/slides.md")
    print(f"  3. Add screenshot entries to {out}/routes.json")
    print(f"  4. Run capture.py --deck {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
